### ISSUE TITLE
credentials.h missing

### ISSUE THREAD

**Issue by sivar2311** [garamizo/Automated-Window-Blinds#1]
Hello @garamizo!

Congratulations on this beautiful project!

You should provide a `credentials.h` (with placeholders).
https://github.com/garamizo/Automated-Window-Blinds/blob/60a63066927e0e0303950f70562770ba5ece1f8e/Arduino/AWB_firmware/AWB_firmware.ino#L33

For security reasons remove the deviceId's from the source code and use a placeholder as well. 
These could also be defined in the `credentials.h`.

https://github.com/garamizo/Automated-Window-Blinds/blob/60a63066927e0e0303950f70562770ba5ece1f8e/Arduino/AWB_firmware/AWB_firmware.ino#L38-L50

**Comment by garamizo** [comment]
Thank you for the words of encouragement and the suggestions!
I addressed them here bdb594b93cfa6876b1b356c212f67f9b535e12d6

Looking forward to see your IOT projects!
